version: "3.1"
services:
  retrosynthesis:
    image: vedoly/ktv-retrosynthesis
    ports:
      - 5000:5000
  generative:
    image: vedoly/ktv-generative
    restart: always
    ports:
      - 5555:5555
  frontend:
    image: vedoly/webapp-do-local
    ports:
      - 80:3000
